name: Build PW App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Pake CLI
        run: npm install -g pake-cli

      - name: Build app
        run: pake https://www.pw.live/study-v2/study --name PWStudy --width 1280 --height 800 --force-internal-navigation --wasm --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" --debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PWStudy-windows
          path: |
            *.exe
            *.msi
